### PR TITLE
replace full lodash package with lodash.clonedeep and typeof checks

### PR DESCRIPTION
**Pull request by danhayden**

### CODE REVIEW

**Comment by danhayden** [comment]
I've just realised I saw you present at LNUG last month.
Great talk by the way, definitely one of the best I've seen!

**Comment by shakyShane** [comment]
Thanks! That's a great compliment as it was my first ever talk - did we chat about your struggle with promises afterwards by any chance?

**Comment by danhayden** [comment]
No problem, hopefully you decide to do some more in the future :)
I didn't speak to you afterwards, must have been someone else.

**Comment by danhayden** [comment]
Is everything okay with this PR is is there anything you would like done differently or that has been missed?

**Comment by shakyShane** [comment]
Thanks!

**Pull request merged**
